import { z } from 'zod';

const emailVerificationConstantsSchema = z.object({
  EMAIL_VERIFICATION_TOKEN_EXPIRES_IN: z.string().default('30m'),
  EMAIL_VERIFICATION_FRONTEND_PATH: z.string().default('/email/verify'),
  EMAIL_VERIFICATION_EMAIL_SENT_MESSAGE: z
    .string()
    .default('이메일 인증이 필요합니다. 인증 이메일을 전송했습니다. 이메일을 확인해주세요.'),
  EMAIL_VERIFICATION_ALREADY_VERIFIED_MESSAGE: z
    .string()
    .default('이미 이메일 인증이 완료되었습니다.'),
  EMAIL_VERIFICATION_SUCCESS_MESSAGE: z.string().default('이메일 인증이 완료되었습니다.'),
  EMAIL_VERIFICATION_INVALID_TOKEN_MESSAGE: z
    .string()
    .default('인증 링크가 유효하지 않거나 만료되었습니다.'),
  EMAIL_VERIFICATION_SEND_FAIL_MESSAGE: z
    .string()
    .default('인증 이메일 전송에 실패했습니다. 잠시 후 다시 시도해주세요.'),
});

const EMAIL_VERIFICATION_CONSTANTS = emailVerificationConstantsSchema.parse({});

export const EMAIL_VERIFICATION_TOKEN_EXPIRES_IN =
  EMAIL_VERIFICATION_CONSTANTS.EMAIL_VERIFICATION_TOKEN_EXPIRES_IN;

export const EMAIL_VERIFICATION_FRONTEND_PATH =
  EMAIL_VERIFICATION_CONSTANTS.EMAIL_VERIFICATION_FRONTEND_PATH;

export const EMAIL_VERIFICATION_EMAIL_SENT_MESSAGE =
  EMAIL_VERIFICATION_CONSTANTS.EMAIL_VERIFICATION_EMAIL_SENT_MESSAGE;

export const EMAIL_VERIFICATION_ALREADY_VERIFIED_MESSAGE =
  EMAIL_VERIFICATION_CONSTANTS.EMAIL_VERIFICATION_ALREADY_VERIFIED_MESSAGE;

export const EMAIL_VERIFICATION_SUCCESS_MESSAGE =
  EMAIL_VERIFICATION_CONSTANTS.EMAIL_VERIFICATION_SUCCESS_MESSAGE;

export const EMAIL_VERIFICATION_INVALID_TOKEN_MESSAGE =
  EMAIL_VERIFICATION_CONSTANTS.EMAIL_VERIFICATION_INVALID_TOKEN_MESSAGE;

export const EMAIL_VERIFICATION_SEND_FAIL_MESSAGE =
  EMAIL_VERIFICATION_CONSTANTS.EMAIL_VERIFICATION_SEND_FAIL_MESSAGE;
